### ISSUE TITLE
contains(@attr, 'value') implementation

### ISSUE THREAD

**Issue by masc-it** [James-LG/Skyscraper#29]
Hello!

I've written a simple implementation for a contains function in `src/xpath/grammar/expressions/primary_expressions/static_function_calls.rs`

```rust
pub(crate) fn eval<'tree>(
        &self,
        context: &XpathExpressionContext<'tree>,
    ) -> Result<XpathItemSet<'tree>, ExpressionApplyError> {
        match &self.name {
            EQName::QName(qname) => match qname {
                QName::PrefixedName(prefixed_name) => {
                   ...
                }
                QName::UnprefixedName(unprefixed_name) => {
                    
                    if unprefixed_name == "contains" {
                        return self.contains(context);
                    }
                    
                    Err(ExpressionApplyError {
                        msg: format!("Unknown function {}", self.name.to_string()),
                    })
                },
            },
            EQName::UriQualifiedName(_) => todo!("FunctionCall::eval UriQualifiedName"),
        }
    }

fn contains<'tree>(&self, context: &XpathExpressionContext<'tree>,) -> Result<XpathItemSet<'tree>, ExpressionApplyError> {
        if self.argument_list.0.len() != 2 {
            return Err(ExpressionApplyError {
                msg: format!("contains function must have 2 arguments: attribute and value. e.g. contains(@class, 'hi')"),
            });
        }

        let attr = self.argument_list.0.get(0).unwrap();
        
        // is there a way to extract a literal argument? 
        // This is the only way I was able to :/
        let value = self.argument_list.0.get(1).unwrap().to_string();
        let value = &value[1..value.len()-2]; // remove '  ' from string representation :/ 
        match attr {
            Argument::ExprSingle(exp) => {
                
                let attr_to_find = exp.to_string().replace("@", "");

                let el_node = context.item.as_node().unwrap()
                    .as_tree_node().unwrap().data.as_element_node().unwrap();
                
                let el_attr = el_node
                    .get_attribute(attr_to_find.as_str());
                
                let contains = match el_attr {
                    Some(a) => {
                        let a = a.to_string();
                        a.contains(&value)
                    },
                    None => false,
                };
                
                if contains {
                    return Ok(xpath_item_set![context.item.clone()]); // I don't think this clone is right.. right?
                }
                // I don't know if there's a better way to return an empty set
                return Ok(crate::xpath::XpathItemSet::new());
            },
            Argument::ArgumentPlaceHolder => {
                todo!()
            },
        };
    }
```

I have no time right now to open a PR, in the meanwhile you can find some questions/doubts in the comments: can you give me some tips? This is the simplest solution I could find of without knowing the new implementation (v0.6.x).

I am open to implement other basic and useful functions such as normalize-space, commonly used in scrapers.

Great work btw and have a nice sunday!

**Comment by James-LG** [comment]
> // is there a way to extract a literal argument? 

This would be the first static function call with an argument, so it is not yet implemented, but it would follow the function conversion rules described [here](https://www.w3.org/TR/2017/REC-xpath-31-20170321/#dt-function-conversion). The description references 'Atomization' which is already partially implemented as `comparison_expressions::func_data(XpathItemSet, XpathItemTree)`, although it may need changes to fit this new use case.

> // I don't think this clone is right.. right?

In general the cloning is required otherwise the `XpathItemTree` would have to be consumed when an expression is applied to it. I expect multiple expressions to be used on a single tree is it's actually much cheaper to clone only the matched nodes than recreating the whole tree every time.

You also can't return a set of references because the atomization process mentioned above creates new items that don't exist in the tree and have no where else to live.

> // I don't know if there's a better way to return an empty set

This function can only ever check the single context item, so it should return a `bool` rather than a set.

---

I'll try to work on the function conversion rules implementation when I have time to make it easier for other function implementations to be contributed.

**Comment by masc-it** [comment]
thanks for the explanation, looking forward to it. 

In the meanwhile, are there any other aspects of the new implementation which one can contribute to? Maybe ordered by difficulty

**Comment by James-LG** [comment]
I think the most important things left to do are some selection axes. They should be relatively easy to implement since there are already examples of other axes and they can be slotted in to an existing match expression.

See `forward_step::eval_forward_axis` and `reverse_step::eval_reverse_axis` functions for the ones left to do.

Be sure to follow the specification for whichever axis you choose to implement: https://www.w3.org/TR/2017/REC-xpath-31-20170321/#axes
